extern ulong	FPcontrol(ulong,ulong);
extern ulong	FPstatus(ulong,ulong);
extern void		FPsave(void*);
extern void		FPrestore(void*);
extern void		Sleep(Rendez*, int (*)(void*), void*);
extern int		Wakeup(Rendez*);
extern void		FPinit(void);
extern void		addprog(Proc*);
extern Block*	adjustblock(Block*, int);
extern Block*	allocb(int);
extern Block*	bl2mem(uchar*, Block*, int);
extern int	blocklen(Block*);
extern char*	c2name(Chan*);
extern int		canlock(Lock*);
extern int		canqlock(QLock*);
extern void		cclose(Chan*);
extern void		chandevinit(void);
extern void		chanfree(Chan*);
extern Dir*		chandirstat(Chan*);
extern void		cinit(void);
extern char*	clipread(void);
extern int		clipwrite(char*);
extern void	(*coherence)(void);
extern void		copen(Chan*);
extern void		cmderror(Cmdbuf*, char*);
extern Block*	concatblock(Block*);
extern int		cread(Chan*, uchar*, int, vlong);
extern void		cwrite(Chan*, uchar*, int, vlong);
extern Chan*	cunique(Chan*);
extern void		cupdate(Chan*, uchar*, int, vlong);
extern char*	cleanname(char*);
extern Chan*	cclone(Chan*);
extern void		closeegrp(Egrp*);
extern void		closefgrp(Fgrp*);
extern void		closepgrp(Pgrp*);
extern void		closesigs(Skeyset*);
extern int		cmount(Chan*, Chan*, int, char*);
extern Chan*	createdir(Chan*, Mhead*);
extern void		cunmount(Chan*, Chan*);
extern int		decref(Ref*);
extern long		devbwrite(Chan*, Block*, ulong);
extern void		devcreate(Chan*, char*, int, ulong);
extern void		devdir(Chan*, Qid, char*, long, char*, long, Dir*);
extern long		devdirread(Chan*, char*, long, Dirtab*, int, Devgen*);
extern void		devinit(void);
extern int		devno(int, int);
extern Dev*		devbyname(char*);
extern void		devpermcheck(char*, ulong, int);
extern void		devremove(Chan*);
extern int		devstat(Chan*, uchar*, int, Dirtab*, int, Devgen*);
extern long		devtabread(Chan*, void*, long, vlong);
extern int		devwstat(Chan*, uchar*, int);
extern Chan*	devattach(int, char*);
extern Block*	devbread(Chan*, long, ulong);
extern Chan*	devclone(Chan*);
extern Devgen	devgen;
extern Chan*	devopen(Chan*, int, Dirtab*, int, Devgen*);
extern Walkqid*	devwalk(Chan*, Chan*, char**, int, Dirtab*, int, Devgen*);
extern void		disfault(void*, char*);
extern void		disinit(void*);
extern int		domount(Chan**, Mhead**);
extern void	drawqlock(void);
extern void	drawqunlock(void);
extern Fgrp*	dupfgrp(Fgrp*);
extern void		egrpcpy(Egrp*, Egrp*);
extern int		emptystr(char*);
extern void		emuinit(void*);
extern int		eqchan(Chan*, Chan*, int);
extern int		eqqid(Qid, Qid);
extern void		error(char*);
extern void		errorf(char*, ...);
#pragma varargck argpos errorf 1
extern void		excinit(void);
extern void		exhausted(char*);
extern int		export(int, char*, int);
extern Chan*	fdtochan(Fgrp*, int, int, int, int);
extern int		findmount(Chan**, Mhead**, int, int, Qid);
extern void		freeb(Block*);
extern void		freeblist(Block*);
extern void		freeskey(Signerkey*);
extern ulong	getcallerpc(void*);
extern ulong	getFPcontrol(void);
extern ulong	getFPstatus(void);
extern void		gkbdputc(Queue*, int);
extern int		incref(Ref*);
extern int		iprint(char*, ...);
extern void		isdir(Chan*);
extern int		isdotdot(char*);
extern int		iseve(void);
extern int		kannounce(char*, char*);
extern int		kdial(char*, char*, char*, int*);
extern void		kproc(char*, void (*)(void*), void*, int);
extern void	kprocinit(Proc*);
extern int		kfgrpclose(Fgrp*, int);
extern void		ksetenv(char*, char*, int);
extern void		kstrcpy(char*, char*, int);
extern void		kstrdup(char**, char*);
extern long		latin1(uchar*, int);
extern void		libinit(char*);
extern void		links(void);
extern void		lock(Lock*);
extern Cmdtab*		lookupcmd(Cmdbuf*, Cmdtab*, int);
extern Block*	mem2bl(uchar*, int);
extern int		memusehigh(void);
extern int		memlow(void);
extern void		mkqid(Qid*, vlong, ulong, int);
extern Qid	mkuqid(Chan*, Uqid*);
extern Chan*		mntauth(Chan*, char*);
extern long		mntversion(Chan*, char*, int, int);
extern void		mountfree(Mount*);
extern void		mousetrack(int, int, int, int);
extern void		muxclose(Mnt*);
extern Chan*	namec(char*, int, int, ulong);
extern Chan*	newchan(void);
extern Cname*	newcname(char*);
extern Egrp*	newegrp(void);
extern Fgrp*	newfgrp(Fgrp*);
extern Mount*	newmount(Mhead*, Chan*, int, char*);
extern Pgrp*	newpgrp(void);
extern Proc*	newproc(void);
extern void		nexterror(void);
extern void		nofence(void);
extern void		notkilled(void);
extern int		openmode(ulong);
extern void		osblock(void);
extern void*		oscmd(char**, int, char*, int*);
extern int		oscmdwait(void*, char*, int);
extern int		oscmdkill(void*);
extern void		oscmdfree(void*);
extern void		oserror(void);
extern void		oserrstr(char*, uint);
extern void		oslongjmp(void*, osjmpbuf, int);
extern long		osmillisec(void);
extern int		osmillisleep(ulong);
extern void		osready(Proc*);
extern int		limbosleep(ulong);
extern vlong	osusectime(void);
extern Block*	packblock(Block*);
extern Block*	padblock(Block*, int);
extern void		panic(char*, ...);
extern Cmdbuf*		parsecmd(char*, int);
extern void		pexit(char*, int);
extern void		pgrpcpy(Pgrp*, Pgrp*);
extern int		progfdprint(Chan*, int, int, char*, int);
extern void		putenvq(char*, char*, int);
extern void		putenvqv(char*, char**, int, int);
extern void		putmhead(Mhead*);
extern Block*	pullupblock(Block*, int);
extern Block*	pullupqueue(Queue*, int);
extern void		qaddlist(Queue*, Block*);
extern Block*	qbread(Queue*, int);
extern long		qbwrite(Queue*, Block*);
extern Queue*		qbypass(void (*)(void*, Block*), void*);
extern int		qcanread(Queue*);
extern void		qclose(Queue*);
extern int		qisclosed(Queue*);
extern int		qconsume(Queue*, void*, int);
extern Block*	qcopy(Queue*, int, ulong);
extern int		qdiscard(Queue*, int);
extern void		qflush(Queue*);
extern void		qfree(Queue*);
extern int		qfull(Queue*);
extern Block*	qget(Queue*);
extern void		qhangup(Queue*, char*);
extern int		qiwrite(Queue*, void*, int);
extern int		qlen(Queue*);
extern void		qlock(QLock*);
extern void		qnoblock(Queue*, int);
extern Queue*	qopen(int, int, void (*)(void*), void*);
extern int		qpass(Queue*, Block*);
extern int		qproduce(Queue*, void*, int);
extern void		qputback(Queue*, Block*);
extern long		qread(Queue*, void*, int);
extern Block*	qremove(Queue*);
extern void		qreopen(Queue*);
extern void		qsetlimit(Queue*, int);
extern int		qstate(Queue*);
extern void		qunlock(QLock*);
extern int		qwindow(Queue*);
extern int		qwrite(Queue*, void*, int);
extern ulong	randomread(void *xp, ulong n);
extern void	randominit(void);
extern int		readkbd(void);
extern int		readnum(ulong, char*, ulong, ulong, int);
extern int		readnum_vlong(ulong, char*, ulong, vlong, int);
extern int		readstr(ulong, char*, ulong, char*);
#define	seconds()	(osusectime()/1000000)
extern void		seterror(char*, ...);
extern void		setid(char*, int);
extern void	setpointer(int, int);
extern char*	skipslash(char*);
extern void		srvrtinit(void);
extern void		swiproc(Proc*, int);
extern Block*	trimblock(Block*, int, int);
extern long		unionread(Chan*, void*, long);
extern void		unlock(Lock*);
extern Uqid*	uqidalloc(Uqidtab*, Chan*);
extern void		uqidinit(Uqidtab*);
extern void		freeuqid(Uqidtab*, Uqid*);
extern void		validname(char*, int);
extern void		validstat(uchar*, int);
extern void		validwstatname(char*);
extern void		vmachine(void*);
extern int		walk(Chan**, char**, int, int, int*);
extern void		cleanexit(int);
extern void		oshostintr(Proc*);
extern void		osenter(void);
extern void		osleave(void);
extern void		oslopri(void);
extern void		ospause(void);
extern void		osyield(void);
extern void		osreboot(char*, char**);
extern ulong	poolmaxsize(void);
extern Pool*	poolmk(char*, int, int, int);
extern void		hnputv(void*, vlong);
extern void		hnputl(void*, ulong);
extern void		hnputs(void*, ushort);
extern vlong		nhgetv(void*);
extern ulong		nhgetl(void*);
extern ushort		nhgets(void*);
extern void*	smalloc(size_t);
extern void*	kmalloc(size_t);
 
/* Namespace Emulation */
extern int		kbind(char*, char*, int);
extern int		kclose(int);
extern int		kcreate(char*, int, ulong);
extern int		kdup(int, int);
extern int		kfstat(int, uchar*, int);
extern int		kfwstat(int, uchar*, int);
extern int		kmount(int, int, char*, int, char*);
extern int		kunmount(char*, char*);
extern int		kopen(char*, int);
extern long		kread(int, void*, long);
extern int		kremove(char*);
extern vlong	kseek(int, vlong, int);
extern int		kstat(char*, uchar*, int);
extern long		kwrite(int, void*, long);
extern int		kwstat(char*, uchar*, int);
extern Dir*		kdirstat(char*);
extern Dir*		kdirfstat(int);
extern int		kdirwstat(char*, Dir*);
extern int		kdirfwstat(int, Dir*);
extern long		kdirread(int, Dir**);
extern int		klisten(char*, char*);

extern Cname*	addelem(Cname*, char*);
extern void		cleancname(Cname*);
extern void		cnameclose(Cname*);

#pragma varargck argpos iprint 1
